theme: minima
title: RESUME
Date: 12-20-2021
author: Steve Starcher
email: stevestarcher@hotmail.com
description: > # this means to ignore newlines until "baseurl:"
 An awesome description for my site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

# social links
github_username:  stevestarcher # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
